# Intenta ejecutar el bloque de c贸digo
try: 
    numerator = 10
    denominator = 0

    result = numerator / denominator 
    print(result)


# Captura cualquier excepci贸n que ocurra durante la ejecuci贸n del codigo.
except:

    print("Error: Denominator cannot be 0.")                                                                                                                                  

# Este bloque se ejecutara siempre, independientemente de si hay una excepci贸n o no.
finally:
    print("This is finally block.")